In [2]:
import pandas as pd

# Created: Hanjie Liu (j13 '24) Fall 2023
# Last Edited: Fall 2023 (j13 '24)

# File Paths
Doesn't require ssh :) (beacause i'm lazy)

Files needed (in files directory):
1. Master Roster spreedsheet (as a csv file) < can probably make this ssh if you want the live file
2. Show order as a txt file. Can see `fall-2023-show-order.txt` as example (the content is just copied off show order spreadsheet however).

In [3]:
# EDIT THIS: FILE PATHS
roster_path = 'files\[Fall 2023] Master Roster - Roster.csv'
show_order_path = 'files/fall-2023-show-order.txt'

# Read files

Get list of dances in show order

In [5]:
# puts the dance names into show order

dance_names = []
# Open the text file and read its content
with open(show_order_path, 'r') as file:
    for line in file:
        # Split each line into columns based on tabs
        columns = line.strip().split('\t')

        # Check if the line has at least two columns (index and dance name)
        if len(columns) >= 2:
            # Extract the dance name from the second column and append to the list
            dance_name = columns[1]
            dance_names.append(dance_name)

# Print the list of dance names
print(dance_names)
print(len(dance_names)) # should be 18
dance_names += ['Choreog', 'Exec'] # add choreog and exec

['Super', 'Dreams of Dai', '90s Love', 'Youth', 'The Eve', 'AYAYAYA', 'A Rainy Dawn', 'Secret', 'Spirit of Ink', 'PINKCHELLA', 'Big Fish', 'VENI VIDI VICI', 'Autumn Ripples', 'Butterfly', 'Broken Melodies', 'The Call of the Past', 'Teddy Bear', 'Blue']
18

In [6]:
# Read the master roster file for membership / drops
df = pd.read_csv(roster_path)
print(set(df.columns[7:-1]) == set(dance_names)) # rows should match up
df

True

,First Name,Nickname,Last Name,Email Address,Year,Program Name,# Dances,Super,Dreams of Dai,90s Love,...,VENI VIDI VICI,Autumn Ripples,Butterfly,Broken Melodies,The Call of the Past,Teddy Bear,Blue,Choreog,Exec,Lions
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,11,13,...,23,13,21,32,10,33,29,22,11,4
1,Abena,NaN,Kyereme-Tuah,abenakt@mit.edu,Sophomore,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abigail,NaN,Xu,agxu@mit.edu,Freshman,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN,NaN
3,Adam,NaN,Zweiger,adamz@mit.edu,Freshman,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN,NaN
4,Addison,NaN,Spiegel,spiegel1@mit.edu,Freshman,NaN,2.0,NaN,NaN,x,...,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Yunbeen,NaN,Bae,yunbeen@mit.edu,Senior,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN
243,Yuru,NaN,Lin,yurulin@mit.edu,Freshman,NaN,2.0,NaN,NaN,drop,...,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,Yutong,NaN,Zhang,zyt0318@mit.edu,Graduate,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,Yuxin,Candy,Xie,yxie25@mit.edu,Junior,Candy Xie,2.0,NaN,late drop,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,Zhixing,Z,Chen,zhixingc@mit.edu,Junior,Z Chen,1.0,drop,NaN,NaN,...,NaN,NaN,drop,x,NaN,NaN,drop,x,NaN,NaN

# Generate Bow Lines

In [9]:
# helper function. prints lists as a pretty string.
def print_list(List):
    string_list = string_names = str(List).replace("'", "").replace("[", "").replace("]", "")
    return string_list

In [7]:
bow_lines = {dance: [] for dance in dance_names}
temp = []
for index, row in df.iterrows():
    # count the last one as the one we want

    for dance in reversed(dance_names):
        if row[dance] == 'x':
            #print("dancer", row['Email Address'], 'in', dance)
            kerb = row['Email Address'].split('@')[0]
            bow_lines[dance].append(kerb)
            break

In [10]:
bow_lines_order = list(reversed(dance_names[:-2])) + dance_names[-2:]

Print result

In [11]:
for line in bow_lines_order:
    names = bow_lines[line]
    string_names = print_list(names)
    print(line, '| ', len(names), ' | ', string_names)

#print(bow_lines)

Blue |  21  |  awmei, liangela, axlin, cszhang, djwyen, dcoello, eyf, elgoldie, fionawsh, gsjau, grace.li.5428, lychee23, juliaxia, ylanaxu, mattfeng, cqimz, muhuaxu, nicolexu, rachelai, xshirley, vivhan
Teddy Bear |  29  |  ahan, aliciali, anicaliu, akim05, emmashi, hannahh, helenzy, isaq, isazeng, jimin24, jinakoh, kyz, marpham, mayabose, linmel, mtxiang, nerwong, nic0les, ningshan, peihua, rachcai, rloha, spei, tndawson, timmybui, valkwek, liangy, ywang00, yunbeen
The Call of the Past |  4  |  emizfliu, lqiao312, peggyy, vzxiao
Broken Melodies |  28  |  agxu, adamz, spiegel1, Aofan, akchang, atripleu, ationg, derchen, ellawang, ewang13, evnkim, fareeds, hgzhang, jackhliu, jeryl, jchen01, jple, lidiap, nlin3405, sabrliu, sfei101, seohyunk, syao26, hanstep, sunsh16e, wenqi22, yeefay, ssuo
Butterfly |  8  |  artliang, ashlyluo, bearii28, csh05, josleen, julieyu, michwu, robinl21
Autumn Ripples |  7  |  solam, amyzhong, ajz, ellieb, gab1108, jasli, keqian
VENI VIDI VICI |  14  |  adithyab, ajiao, aw4ng, ahyip, cbrian, bryanmw, ivywu, mmc17, msz, rxiong22, pxy, ychen1, icecream, yurulin
Big Fish |  16  |  angela4z, annliu22, annachan, czlu, cat2510, cyung, dorazhou1, heidiz, itgeld, jzhang36, jolidou, rinacao, sjcai, swenjin, lilyz968, yuexu128
PINKCHELLA |  12  |  abenakt, amberluo, rjcan, jennyxz, knreal, melodyyu, livlee, sabelle, yuhecui, lucyhao, zyt0318, yxie25
Spirit of Ink |  7  |  ash3960, byliu, catwang, iwshi, izarv, kakura, wsw23
Secret |  8  |  heamy, bpyo, jcsohn, klpan, carluci, leecindy, samslee, seok
A Rainy Dawn |  2  |  ayl27, sqcheng
AYAYAYA |  10  |  cateli, iceco, ixzhu, katdou, katdou, kyli648, kchap, lwl, yunomi, sophielw
The Eve |  19  |  amberyw, achin4, bchen27, chriszh, zeric, fengqiu, halih, htfan, jessding, wujl, jett, lcai12, cshell, rychang, siyong, tcqian, tfeng, tmwillin, williamx
Youth |  1  |  sophie05
90s Love |  4  |  alexisy, azf, gnsmith, maximna
Dreams of Dai |  0  |
Super |  6  |  ashleyke, branchen, jinj, jeli, ntsao, ashiyu
Choreog |  18  |  angao, yangela, sh1639, luclaire, cmzheng, zcynthia, elizke, ellief, ehua, hwl, inorik, janabel, kzl, luisap, rjloh, solcu483, sravanid, zhixingc
Exec |  11  |  alexishu, aliyang, chhyun, dorah, j13, kinglyw, reinaw03, zhengr, sebaszhu, twangst, xinghui

Use this for easy pasting into sheets

In [12]:
# print to easily paste dance names -----------------------------------------------------------
# [print(line) for line in bow_lines_order] 

# print to easliy paste bowline lengths -----------------------------------------------------------
# [print(len(bow_lines[line])) for line in bow_lines_order] 

# print to easily paste bowline people -----------------------------------------------------------
# [print( print_list(bow_lines[line]) ) for line in bow_lines_order]

awmei, liangela, axlin, cszhang, djwyen, dcoello, eyf, elgoldie, fionawsh, gsjau, grace.li.5428, lychee23, juliaxia, ylanaxu, mattfeng, cqimz, muhuaxu, nicolexu, rachelai, xshirley, vivhan
ahan, aliciali, anicaliu, akim05, emmashi, hannahh, helenzy, isaq, isazeng, jimin24, jinakoh, kyz, marpham, mayabose, linmel, mtxiang, nerwong, nic0les, ningshan, peihua, rachcai, rloha, spei, tndawson, timmybui, valkwek, liangy, ywang00, yunbeen
emizfliu, lqiao312, peggyy, vzxiao
agxu, adamz, spiegel1, Aofan, akchang, atripleu, ationg, derchen, ellawang, ewang13, evnkim, fareeds, hgzhang, jackhliu, jeryl, jchen01, jple, lidiap, nlin3405, sabrliu, sfei101, seohyunk, syao26, hanstep, sunsh16e, wenqi22, yeefay, ssuo
artliang, ashlyluo, bearii28, csh05, josleen, julieyu, michwu, robinl21
solam, amyzhong, ajz, ellieb, gab1108, jasli, keqian
adithyab, ajiao, aw4ng, ahyip, cbrian, bryanmw, ivywu, mmc17, msz, rxiong22, pxy, ychen1, icecream, yurulin
angela4z, annliu22, annachan, czlu, cat2510, cyung, dorazhou1, heidiz, itgeld, jzhang36, jolidou, rinacao, sjcai, swenjin, lilyz968, yuexu128
abenakt, amberluo, rjcan, jennyxz, knreal, melodyyu, livlee, sabelle, yuhecui, lucyhao, zyt0318, yxie25
ash3960, byliu, catwang, iwshi, izarv, kakura, wsw23
heamy, bpyo, jcsohn, klpan, carluci, leecindy, samslee, seok
ayl27, sqcheng
cateli, iceco, ixzhu, katdou, katdou, kyli648, kchap, lwl, yunomi, sophielw
amberyw, achin4, bchen27, chriszh, zeric, fengqiu, halih, htfan, jessding, wujl, jett, lcai12, cshell, rychang, siyong, tcqian, tfeng, tmwillin, williamx
sophie05
alexisy, azf, gnsmith, maximna

ashleyke, branchen, jinj, jeli, ntsao, ashiyu
angao, yangela, sh1639, luclaire, cmzheng, zcynthia, elizke, ellief, ehua, hwl, inorik, janabel, kzl, luisap, rjloh, solcu483, sravanid, zhixingc
alexishu, aliyang, chhyun, dorah, j13, kinglyw, reinaw03, zhengr, sebaszhu, twangst, xinghui

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]